blueprint:
  name: blueprints-starter-example
  schema_version: "1.0.0"
  description: "Sample blueprint to demonstrate linking workspaces and passing vars"
  inputs:
    - resource_group
    - region
    - sample_var
    - boolian_var
    - list_any_flow_scalar
    - list_any_block_scalar
    - docker_ports

  outputs:
    - key: blueprint-output
      value: $workitem.terraform_workitem2.outputs.nested_complex
  source:
    git_repo_url: "https://github.ibm.com/schematics-solution"
    #git_release: "v1.0.1"
    git_branch: "main"
    workitems:
      - name: terraform_workitem1
        layer: test
        source:
          source_type: github
          git_folder: "blueprints-starter/tf-inputs-outputs"
          git_branch: "master"
        inputs:
          # default string
          - key: TF_VERSION
            value: 1.0
          - key: sample_var
            value: $blueprint.sample_var
            # default string

          - key: image_id
            value: ami-image
            # HCL type: list(any) passed as flow scalar double-quoted
          - key: list_any_flow_scalar
            value: $blueprint.list_any_flow_scalar
            type: list(any)

            # HCL type: list(any) passed as block scalar double-quoted
          - key: list_any_block_scalar
            value: $blueprint.list_any_block_scalar
            type: list(any)

          - key: docker_ports
            value: $blueprint.docker_ports
            type: |
              list(object({
                internal = number
                external = number
                protocol = string
              })
        outputs:
          - key: nested_complex
          - key: test_tuple

      - name: terraform_workitem2
        layer: test
        source:
          source_type: github
          git_folder: "blueprints-starter/tf-inputs-outputs"
          git_branch: "master"
        inputs:
          # default string
          - key: TF_VERSION
            value: 1.0
          - key: sample_var
            value: $blueprint.sample_var
            # default string

          - key: image_id
            value: ami-image
            # HCL type: list(any) passed as flow scalar double-quoted
          - key: list_any_flow_scalar
            value: $blueprint.list_any_flow_scalar
            type: list(any)

            # HCL type: list(any) passed as block scalar double-quoted
          - key: list_any_block_scalar
            value: $blueprint.list_any_block_scalar
            type: list(any)

          - key: docker_ports
            value: $workitem.terraform_workitem1.nested_complex
            type: |
              list(object({
                internal = number
                external = number
                protocol = string
              })
        outputs:
          - key: nested_complex
          - key: test_tuple
